;-------------------------------------------------------------------------------

; Exercise 1.15

; The sine of an angle (specified in radians) can be computed by making use of
; of the approximation sin(x) ~ x if x is sufficiently small, and the
; trigonometric identity sin(x) = 3sin(x/3) - 4sin(x/3)^3 to reduce the size of
; the argument of sin. (For purposes of this exercise and angle is considered
; "sufficiently small" if its magnitude is not greater than 0.1 in radians.)
; These ideas are incorporated in the following procedures:

(define (cube x)
  (* x x x))

(define (p x)
  (- (* 3 x) (* 4 (cube x))))

(define (sine angle)
  (display angle)
  (newline)
  (if (<= (abs angle) 0.1)
      angle
      (p (sine (/ angle 3.0)))))

; (a) How many times is the procedure p applied when (sine 12.15) is evaluated?

(define (logarithm b x)
  (/ (log x) (log b)))

(define (how-many-times? angle)
  (ceiling (logarithm 3 (/ angle 0.1))))

(how-many-times? 12.15) ; => 5.0

; (b) What is the order of growth in space and number of steps (as a function of
; a) used by the process generated by the sine procedure when (sine a) is
; evaluated?

; O(log(a))
